trigger:
- master

pr:
- master

pool: Default

stages:
  - stage: Build
    jobs:
      - job: Build_App
        steps:
          - task: CopyFiles@2
            inputs:
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - script: pip install poetry
            displayName: Install poetry
          
          - script: python -m poetry install && python -m poetry shell
            displayName: Install dependencies

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'PyDo'
              publishLocation: 'Container'