trigger:
- master

pr:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build_App
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: CopyFiles@2
            inputs:
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
              addToPath: true
              architecture: 'x64'

          - script: pip install poetry
            displayName: Install poetry
          
          - script: poetry install && poetry shell
            displayName: Install dependencies

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'PyDo'
              publishLocation: 'Container'