"""Make list_id not nullable

Revision ID: 9edf8ca5a3c5
Revises: f3f49eb28ea7
Create Date: 2021-07-05 19:27:19.114599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9edf8ca5a3c5'
down_revision = 'f3f49eb28ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
