"""Added Priority field

Revision ID: c6a42e8abb37
Revises: 57672ef7848e
Create Date: 2021-07-05 14:50:11.825429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a42e8abb37'
down_revision = '57672ef7848e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('priority', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_todo_priority'), 'todo', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_priority'), table_name='todo')
    op.drop_column('todo', 'priority')
    # ### end Alembic commands ###
